/* Normalise the iGOT Karmayogi catalogue export into src/catalogue.js.
   Run: node tools/ingest-igot.mjs data/courses.json

   The export carries name, description, duration, identifier and source.
   It carries no competency tags, no proficiency level, no language flag and
   no engagement telemetry — those are derived here (level, language) or in
   the engine at runtime (competency mapping). Nothing is invented: fields
   the export does not contain are simply absent. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(process.argv[2] || join(here, '..', 'data', 'courses.json'));
const raw = JSON.parse(readFileSync(src, 'utf8'));
const rows = (raw.content || []).filter((r) => r.primaryCategory === 'Course');

const clean = (s) =>
  String(s || '')
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/\s+/g, ' ')
    .trim();

const LOW = /\b(introduc\w*|basics?|basic|fundamental\w*|awareness|beginner|overview|primer|orientation|induction|part 1|module 1)\b/i;
const MID = /\b(applied|practitioner|professional|certification|hands.?on|workshop|practical|implementation|for officials)\b/i;
const HIGH = /\b(advanced|expert|mastering|master ?class|in-depth|deep dive|specialis\w*|specializ\w*|strategic|leadership programme)\b/i;

/* iGOT is largely microlearning — the median module runs about an hour — so
   duration is a weak proficiency signal here. Register in the title and
   abstract carries most of it, with length as a secondary bump. */
function levelOf(hours, text) {
  let lv = 2;
  if (LOW.test(text)) lv = 1;
  if (MID.test(text)) lv = 3;
  if (HIGH.test(text)) lv = 4;
  if (hours >= 8) lv += 1;
  if (hours >= 25) lv += 1;
  return Math.max(1, Math.min(5, lv));
}

const seen = new Map();
let dropped = { junk: 0, duplicate: 0, empty: 0 };

for (const r of rows) {
  const title = clean(r.name);
  const text = clean(r.description);

  // one placeholder record ships in the export
  if (/- C\d{5,}$/.test(title) || /^Course - .* summary$/i.test(text)) { dropped.junk++; continue; }
  if (!title) { dropped.empty++; continue; }

  const key = title.toLowerCase();
  const secs = Number(r.duration) || 0;
  const hours = Math.max(1, Math.round(secs / 3600));
  const blob = title + ' ' + text;

  const rec = {
    id: String(r.identifier || '').trim(),
    title,
    provider: clean(r.source) || 'iGOT Karmayogi',
    secs,
    hours,
    lang: /[ऀ-ॿ]/.test(blob) ? 'HI' : 'EN',
    level: levelOf(hours, blob),
    text
  };

  const prev = seen.get(key);
  if (prev) {
    dropped.duplicate++;
    // keep whichever record carries the richer abstract
    if (rec.text.length > prev.text.length) seen.set(key, rec);
    continue;
  }
  seen.set(key, rec);
}

const out = [...seen.values()];
const esc = (s) => JSON.stringify(s);
const lines = out.map(
  (c) => `[${esc(c.id)},${esc(c.title)},${esc(c.provider)},${c.secs},${esc(c.lang)},${c.level},${esc(c.text)}]`
);

const body = `/* ===========================================================
   iGOT Karmayogi catalogue — normalised from the platform export.
   Generated by tools/ingest-igot.mjs. Do not edit by hand.

   Columns: [ identifier, title, provider, durationSeconds, language,
              level, abstract ]

   Level is derived from duration and title register; language from the
   presence of Devanagari. Competency mapping is NOT stored here — it is
   computed at runtime by the same TF-IDF engine that powers retrieval,
   so the mapping is inspectable rather than asserted.
   =========================================================== */
(function (NX) {
NX.IGOT_COLUMNS = ['id', 'title', 'provider', 'secs', 'lang', 'level', 'text'];
NX.IGOT_RAW = [
${lines.join(',\n')}
];
})(window.NX = window.NX || {});
`;

mkdirSync(join(here, '..', 'src'), { recursive: true });
writeFileSync(join(here, '..', 'src', 'catalogue.js'), body);

const byProvider = out.reduce((m, c) => ((m[c.provider] = (m[c.provider] || 0) + 1), m), {});
console.log(`source rows      ${rows.length}`);
console.log(`dropped          junk ${dropped.junk} · duplicate ${dropped.duplicate} · empty ${dropped.empty}`);
console.log(`written          ${out.length} modules -> src/catalogue.js`);
console.log(`providers        ${Object.keys(byProvider).length}`);
console.log(`hindi modules    ${out.filter((c) => c.lang === 'HI').length}`);
console.log(`levels           ${[1, 2, 3, 4, 5].map((l) => l + ':' + out.filter((c) => c.level === l).length).join('  ')}`);
console.log(`median hours     ${out.map((c) => c.hours).sort((a, b) => a - b)[Math.floor(out.length / 2)]}`);
